package mmo.materialdata.fairy
{
	import mmo.framework.domain.fairy.Fairy;
	import mmo.framework.domain.fairy.FairyLeaderSkill;
	import mmo.framework.domain.fairy.Fairys;
	import mmo.framework.domain.fairy.FairysType;
	import mmo.framework.domain.fairy.FairysUseType;

	public class FairyLeaderSkillsData
	{
		public function FairyLeaderSkillsData()
		{
		}
		
		/**
		 * 注意：第一行数据不能删除
		 * "{0}":new FairyLeaderSkill({0}, "{1}", "{3}"),
		 */	
		public static const data:Object = {
			"0":new FairyLeaderSkill(0, "", "无"),
			
			//----------------------------黄金分割线------------------------
			
			//exportData part begin

			"1":new FairyLeaderSkill(1, "火焰能量", "火属性精灵造成的普通攻击伤害变为原本的1.5倍"),
			"2":new FairyLeaderSkill(2, "爆炎能量", "火属性精灵造成的普通攻击伤害变为原本的2倍"),
			"3":new FairyLeaderSkill(3, "碧水能量", "水属性精灵造成的普通攻击伤害变为原本的1.5倍"),
			"4":new FairyLeaderSkill(4, "激流能量", "水属性精灵造成的普通攻击伤害变为原本的2倍"),
			"5":new FairyLeaderSkill(5, "青木能量", "木属性精灵造成的普通攻击伤害变为原本的1.5倍"),
			"6":new FairyLeaderSkill(6, "大地能量", "木属性精灵造成的普通攻击伤害变为原本的2倍"),
			"7":new FairyLeaderSkill(7, "闪光能量", "光属性精灵造成的普通攻击伤害变为原本的1.5倍"),
			"8":new FairyLeaderSkill(8, "烈阳能量", "光属性精灵造成的普通攻击伤害变为原本的2倍"),
			"9":new FairyLeaderSkill(9, "黑暗能量", "暗属性精灵造成的普通攻击伤害变为原本的1.5倍"),
			"10":new FairyLeaderSkill(10, "深渊能量", "暗属性精灵造成的普通攻击伤害变为原本的2倍"),
			"11":new FairyLeaderSkill(11, "初级防御", "受到的所有伤害减少10%"),
			"12":new FairyLeaderSkill(12, "初级防御·火", "受到的火属性伤害减少20%"),
			"13":new FairyLeaderSkill(13, "初级防御·水", "受到的水属性伤害减少20%"),
			"14":new FairyLeaderSkill(14, "初级防御·木", "受到的木属性伤害减少20%"),
			"15":new FairyLeaderSkill(15, "初级防御·光", "受到的光属性伤害减少20%"),
			"16":new FairyLeaderSkill(16, "初级防御·暗", "受到的暗属性伤害减少20%"),
			"17":new FairyLeaderSkill(17, "中极防御", "受到的所有伤害减少20%"),
			"18":new FairyLeaderSkill(18, "爆炎壁垒", "受到的火属性伤害减半"),
			"19":new FairyLeaderSkill(19, "激流壁垒", "受到的水属性伤害减半"),
			"20":new FairyLeaderSkill(20, "大地壁垒", "受到的木属性伤害减半"),
			"21":new FairyLeaderSkill(21, "烈阳壁垒", "受到的光属性伤害减半"),
			"22":new FairyLeaderSkill(22, "深渊壁垒", "受到的暗属性伤害减半"),
			"23":new FairyLeaderSkill(23, "王者之力", "生命值为满值时，普通攻击伤害变为3倍"),
			"24":new FairyLeaderSkill(24, "治愈祈祷", "每次消除宝珠时，回复一定量的生命值"),
			"25":new FairyLeaderSkill(25, "潜在之力", "生命值为满值时，普通攻击伤害变为1.5倍"),
			"26":new FairyLeaderSkill(26, "圣愈祈祷", "每次消除宝珠时，回复较多的生命值"),
			"27":new FairyLeaderSkill(27, "天愈祈祷", "每次消除宝珠时，回复大量的生命值"),
			"28":new FairyLeaderSkill(28, "真红的怒吼", "平衡类型精灵的攻击力变为2.5倍"),
			"29":new FairyLeaderSkill(29, "苍蓝的威严", "平衡类型精灵的生命值变为2倍"),
			"30":new FairyLeaderSkill(30, "盖亚的守护", "平衡类型精灵的回复力变为2.5倍"),
			"31":new FairyLeaderSkill(31, "神光的激昂", "神类型精灵的攻击力变为2倍"),
			"32":new FairyLeaderSkill(32, "英灵的守护", "精英类型精灵的生命值变为2倍"),
			"33":new FairyLeaderSkill(33, "宝石爆裂", "攻击类型精灵的攻击力变为2倍"),
			"34":new FairyLeaderSkill(34, "苍之怒", "体力类精灵的攻击力变为2倍"),
			"35":new FairyLeaderSkill(35, "苍之怒吼", "体力类精灵的攻击力变为2.5倍"),
			"36":new FairyLeaderSkill(36, "翠之风", "平衡类精灵的生命值和回复力变为1.5倍"),
			"37":new FairyLeaderSkill(37, "翠之岚", "平衡类精灵的攻击力、生命值和回复力变为1.5倍"),
			"38":new FairyLeaderSkill(38, "炎之辉", "体力类精灵生命值变为1.5倍"),
			"39":new FairyLeaderSkill(39, "炎之圣辉", "体力类精灵生命值变为2倍"),
			"40":new FairyLeaderSkill(40, "光明之心", "回复类精灵的攻击力变为2倍"),
			"41":new FairyLeaderSkill(41, "光明之刃", "回复类精灵的攻击力变为2.5倍"),
			"42":new FairyLeaderSkill(42, "黑暗毒雾", "每次消除宝珠，额外进行一次攻击"),
			"43":new FairyLeaderSkill(43, "幽冥毒雾", "每次消除宝珠，额外进行一次大攻击"),
			"44":new FairyLeaderSkill(44, "三角阵型", "火、水、木三种属性同时攻击时，全部精灵攻击力变为2.5倍"),
			"45":new FairyLeaderSkill(45, "海豚之力", "水属性精灵的攻击力变为1.5倍"),
			"46":new FairyLeaderSkill(46, "夏薇夷之力", "水属性精灵的攻击力和回复力变为1.5倍"),
			"47":new FairyLeaderSkill(47, "炎之魂", "火属性精灵的攻击力和回复力变为1.5倍"),
			"48":new FairyLeaderSkill(48, "红莲之魂", "火属性精灵的攻击力和回复力变为2倍"),
			"49":new FairyLeaderSkill(49, "海之魂", "水属性精灵的攻击力和回复力变为1.5倍"),
			"50":new FairyLeaderSkill(50, "七海之魂", "水属性精灵的攻击力和回复力变为2倍"),
			"51":new FairyLeaderSkill(51, "地之魂", "木属性精灵的攻击力和回复力变为1.5倍"),
			"52":new FairyLeaderSkill(52, "生命之魂", "木属性精灵的攻击力和回复力变为2倍"),
			"53":new FairyLeaderSkill(53, "光之魂", "光属性精灵的攻击力和回复力变为1.5倍"),
			"54":new FairyLeaderSkill(54, "雷电之魂", "光属性精灵的攻击力和回复力变为2倍"),
			"55":new FairyLeaderSkill(55, "冥之魂", "暗属性精灵的攻击力和回复力变为1.5倍"),
			"56":new FairyLeaderSkill(56, "冥王之魂", "暗属性精灵的攻击力和回复力变为2倍"),
			"57":new FairyLeaderSkill(57, "绵羊之力", "木属性精灵的生命值变为2倍"),
			"58":new FairyLeaderSkill(58, "苏歌兰之力", "木属性精灵的生命值和回复力变为2倍"),
			"59":new FairyLeaderSkill(59, "军犬之力", "当血量低于75%，暗属性精灵的攻击力变为1.5倍"),
			"60":new FairyLeaderSkill(60, "希伯莉娅之力", "当血量低于75%，暗属性精灵的攻击力变为2.5倍"),
			"61":new FairyLeaderSkill(61, "狮舞之力", "火属性精灵的攻击力变为1.5倍"),
			"62":new FairyLeaderSkill(62, "钟华之力", "火属性精灵的攻击力和生命值变为1.5倍"),
			"63":new FairyLeaderSkill(63, "萌豹之力", "光属性精灵的攻击力变为1.5倍"),
			"64":new FairyLeaderSkill(64, "艾奇之力", "光属性精灵的攻击力和生命值变为1.5倍"),
			"65":new FairyLeaderSkill(65, "三色同仁", "火、光、暗三种属性同时攻击时，全部精灵攻击力变为2.5倍"),
			"66":new FairyLeaderSkill(66, "月之生机", "水属性精灵的生命值变为2倍"),
			"67":new FairyLeaderSkill(67, "月光源泉", "水属性精灵的生命值变为2.5倍"),
			"68":new FairyLeaderSkill(68, "神之祈祷", "每次消除宝珠时，回复超大量的生命值"),
			"69":new FairyLeaderSkill(69, "暗夜壁垒", "受到的暗属性伤害减半"),
			"70":new FairyLeaderSkill(70, "绝对神域", "满血时受到所有伤害减少80%"),
			"71":new FairyLeaderSkill(71, "魔炎掌控", "火属性精灵的攻击力和回复力变为1.5倍"),
			"72":new FairyLeaderSkill(72, "真·红莲掌控", "火属性精灵的生命值、攻击力和回复力变为1.5倍"),
			"73":new FairyLeaderSkill(73, "式水之术", "水属性精灵的攻击力和回复力变为1.5倍"),
			"74":new FairyLeaderSkill(74, "真·式水之术", "水属性精灵的生命值、攻击力和回复力变为1.5倍"),
			"75":new FairyLeaderSkill(75, "大地巫术", "木属性精灵的攻击力和回复力变为1.5倍"),
			"76":new FairyLeaderSkill(76, "真·大地巫术", "木属性精灵的生命值、攻击力和回复力变为1.5倍"),
			"77":new FairyLeaderSkill(77, "彩虹糖攻击", "水、木、暗三种属性同时攻击时，全部精灵攻击力变为2.5倍"),
			"78":new FairyLeaderSkill(78, "南瓜守护", "火属性精灵的生命值变为2.5倍"),
			"79":new FairyLeaderSkill(79, "战意澎湃", "攻击类型精灵的攻击力和回复力变为1.5倍"),
			"80":new FairyLeaderSkill(80, "姬神的反击", "当血量低于30%，所有精灵的攻击力变为2.5倍"),
			"81":new FairyLeaderSkill(81, "火圣诞的祝福", "火属性精灵的生命值和回复力变为2倍"),
			"82":new FairyLeaderSkill(82, "水圣诞的祝福", "水属性精灵的生命值和回复力变为2倍"),
			"83":new FairyLeaderSkill(83, "木圣诞的祝福", "木属性精灵的生命值和回复力变为2倍"),
			"84":new FairyLeaderSkill(84, "执着", "当受到一次致命攻击时，血量为总血量的50%或以上，将会以1点血量生还"),
			"85":new FairyLeaderSkill(85, "爱神之力", "当血量不足80%时，所有精灵的攻击力变为3倍"),
			"86":new FairyLeaderSkill(86, "炎之战意", "火属性精灵的生命值和攻击力变为2倍"),
			"87":new FairyLeaderSkill(87, "冰之祝福", "水属性精灵的生命值和攻击力变为2倍"),
			"88":new FairyLeaderSkill(88, "天父圣光", "木属性精灵的生命值和攻击力变为2倍"),
			"89":new FairyLeaderSkill(89, "雷之护盾", "光属性精灵的生命值和攻击力变为2倍"),
			"90":new FairyLeaderSkill(90, "暗黑领域", "暗属性精灵的生命值和攻击力变为2倍"),
			"91":new FairyLeaderSkill(91, "神王之力", "光属性和神类型精灵的攻击力变为2.5倍"),
			"92":new FairyLeaderSkill(92, "炎之舞", "当生命值为满值时，火属性攻击力变为2.5倍"),
			"93":new FairyLeaderSkill(93, "绯天之舞", "当生命值为满值时，火属性攻击力变为3倍"),
			"94":new FairyLeaderSkill(94, "龙之舞", "当生命值为满值时，水属性攻击力变为2.5倍"),
			"95":new FairyLeaderSkill(95, "升龙之舞", "当生命值为满值时，水属性攻击力变为3倍"),
			"96":new FairyLeaderSkill(96, "灵之舞", "当生命值为满值时，木属性攻击力变为2.5倍"),
			"97":new FairyLeaderSkill(97, "升灵之舞", "当生命值为满值时，木属性攻击力变为3倍"),
			"98":new FairyLeaderSkill(98, "光之舞", "当生命值为满值时，光属性攻击力变为2.5倍"),
			"99":new FairyLeaderSkill(99, "麒麟之舞", "当生命值为满值时，光属性攻击力变为3倍"),
			"100":new FairyLeaderSkill(100, "殇之舞", "当生命值为满值时，暗属性攻击力变为2.5倍"),
			"101":new FairyLeaderSkill(101, "虎殇之舞", "当生命值为满值时，暗属性攻击力变为3倍"),
			"102":new FairyLeaderSkill(102, "战女神的祝福", "当生命值大于或等于80%，火属性精灵攻击力变为2.8倍"),
			"103":new FairyLeaderSkill(103, "锁链之舞", "水属性精灵的攻击力变为2.5倍"),
			"104":new FairyLeaderSkill(104, "抚谷之心", "木属性精灵的攻击力变为2.5倍"),
			"105":new FairyLeaderSkill(105, "太阳之力", "光属性精灵的攻击力变为2.5倍"),
			"106":new FairyLeaderSkill(106, "紫月之力", "当生命值大于或等于80%时，暗属性精灵攻击力变为3倍"),
			"107":new FairyLeaderSkill(107, "草莓果酱", "受到的火属性伤害减少50%"),
			"108":new FairyLeaderSkill(108, "蓝莓果酱", "受到的水属性伤害减少50%"),
			"109":new FairyLeaderSkill(109, "苹果果酱", "受到的木属性伤害减少50%"),
			"110":new FairyLeaderSkill(110, "芒果果酱", "受到的光属性伤害减少50%"),
			"111":new FairyLeaderSkill(111, "葡萄果酱", "受到的暗属性伤害减少50%"),
			"112":new FairyLeaderSkill(112, "冰淇淋大挑战", "连击数达到3以上时，所有宠物的攻击力变为2倍"),
			"113":new FairyLeaderSkill(113, "灵猫舞动", "光属性的生命值提升，攻击力变为2倍"),
			"114":new FairyLeaderSkill(114, "幽冥之猫", "暗属性的生命值提升，攻击力变为2倍"),
			"115":new FairyLeaderSkill(115, "天狐之魅", "火属性的生命值提升，攻击力变为2倍"),
			"116":new FairyLeaderSkill(116, "海之梦", "水属性的生命值提升，攻击力变为2倍"),
			"117":new FairyLeaderSkill(117, "森之幻", "木属性的生命值提升，攻击力变为2倍"),
			"118":new FairyLeaderSkill(118, "炽焰神谕", "火属性的生命值提升，攻击力变为3倍"),
			"119":new FairyLeaderSkill(119, "碧水神谕", "水属性的生命值提升，攻击力变为3倍"),
			"120":new FairyLeaderSkill(120, "岚风神谕", "木属性的生命值提升，攻击力变为3倍"),
			"121":new FairyLeaderSkill(121, "烈阳神谕", "光属性的生命值提升，攻击力变为3倍"),
			"122":new FairyLeaderSkill(122, "混沌神谕", "暗属性的生命值提升，攻击力变为3倍"),
			"123":new FairyLeaderSkill(123, "无极", "当生命值为满时，神类型精灵攻击力变为3倍"),
			"124":new FairyLeaderSkill(124, "冶金之力", "当生命值大于或等于80%时，火属性精灵攻击力变为3倍"),
			"125":new FairyLeaderSkill(125, "圣枪守护", "当生命值大于或等于50%时，光属性攻击力和回复力2.5倍"),
			"126":new FairyLeaderSkill(126, "女王之魅", "精英类型精灵攻击力变为3倍"),
			"127":new FairyLeaderSkill(127, "灵之魔力", "水属性精灵生命值变为1.5倍，攻击力变为2倍"),
			"128":new FairyLeaderSkill(128, "龙之魔力", "木属性精灵生命值变为1.5倍，攻击力变为2倍"),
			"129":new FairyLeaderSkill(129, "辉之魔力", "当生命值大于或等于50%时，光属性攻击力3.5倍，回复力1.5倍"),
			"130":new FairyLeaderSkill(130, "剑之魔力", "当生命值大于或等于50%时，暗属性攻击力3.5倍，回复力1.5倍"),
			"131":new FairyLeaderSkill(131, "赤炼战意", "火属性、体力类型精灵的生命值和攻击力变为2倍"),
			"132":new FairyLeaderSkill(132, "寒冰祝福", "水属性、回复类型精灵的生命值和攻击力变为2倍"),
			"133":new FairyLeaderSkill(133, "圣天之光", "木属性、平衡类型精灵的生命值和攻击力变为2倍"),
			"134":new FairyLeaderSkill(134, "狂雷护盾", "光属性、攻击类型精灵的生命值和攻击力变为2倍"),
			"135":new FairyLeaderSkill(135, "堕狱领域", "暗属性、精英类型精灵的生命值和攻击力变为2倍"),
			"136":new FairyLeaderSkill(136, "爆炎神域", "受到的火属性伤害减少60%"),
			"137":new FairyLeaderSkill(137, "大地神域", "受到的木属性伤害减少60%"),
			"138":new FairyLeaderSkill(138, "激流神域", "受到的水属性伤害减少60%"),
			"139":new FairyLeaderSkill(139, "帝王神域", "受到的光属性伤害减少60%"),
			"140":new FairyLeaderSkill(140, "深渊神域", "受到的暗属性伤害减少60%"),
			"141":new FairyLeaderSkill(141, "白羊守护", "回复类型生命值和攻击力变为2倍"),
			"142":new FairyLeaderSkill(142, "金牛守护", "体力类型攻击力和回复力变为2倍"),
			"143":new FairyLeaderSkill(143, "摩羯守护", "攻击类型精灵攻击力和回复力变为2倍"),
			"144":new FairyLeaderSkill(144, "酷蛋之力", "木属性精灵生命值变为1.5倍，攻击力变为2倍"),
			"145":new FairyLeaderSkill(145, "笨蛋之力", "光属性精灵生命值变为1.5倍，攻击力变为2倍"),
			"146":new FairyLeaderSkill(146, "元蛋之力", "水属性精灵生命值变为1.5倍，攻击力变为2倍"),
			"147":new FairyLeaderSkill(147, "圣·白羊守护", "回复类型精灵生命值变为2倍，攻击力变为2.5倍"),
			"148":new FairyLeaderSkill(148, "圣·金牛守护", "体力类型精灵回复力变为2倍，攻击力变为2.5倍"),
			"149":new FairyLeaderSkill(149, "圣·摩羯守护", "攻击类型精灵回复力变为2倍，攻击力变为2.5倍"),
			"150":new FairyLeaderSkill(150, "双子守护", "攻击类型精灵攻击力和回复力变为2倍"),
			"151":new FairyLeaderSkill(151, "王者之域", "火属性和暗属性攻击力和回复力变为2.5倍"),
			"152":new FairyLeaderSkill(152, "巨蟹守护", "平衡类型生命值、攻击力、回复力变为1.5倍"),
			"153":new FairyLeaderSkill(153, "天蝎守护", "精英类型攻击力和回复力变为2倍"),
			"154":new FairyLeaderSkill(154, "处女守护", "受到的水属性伤害减少50%"),
			"155":new FairyLeaderSkill(155, "水瓶守护", "当生命值大于或等于50%时，回复类精灵攻击力2.5倍"),
			"156":new FairyLeaderSkill(156, "狮子守护", "当生命值大于或等于50%时，体力类型攻击力2.5倍"),
			"157":new FairyLeaderSkill(157, "双鱼守护", "当生命值大于或等于50%时，精英类型攻击力2.5倍"),
			"158":new FairyLeaderSkill(158, "天秤守护", "当生命值大于或等于50%时，攻击类型攻击力2.5倍"),
			"159":new FairyLeaderSkill(159, "射手守护", "受到的光属性伤害减少50%"),
			"160":new FairyLeaderSkill(160, "无双之力", "火属性精灵生命值和回复力1.3倍，火、木、暗属性同时攻击，攻击力3.5倍"),
			"161":new FairyLeaderSkill(161, "水雷之力", "水属性精灵生命值和回复力1.3倍，水、火、光属性同时攻击，攻击力3.5倍"),
			"162":new FairyLeaderSkill(162, "武圣之力", "木属性精灵生命值和回复力1.3倍，木、光、暗属性同时攻击，攻击力3.5倍"),
			"163":new FairyLeaderSkill(163, "魔音之力", "光属性精灵生命值和回复力1.3倍，任意四种属性同时攻击，攻击力4倍"),
			"164":new FairyLeaderSkill(164, "联·诛", "暗属性精灵生命值和回复力1.3倍，五种属性同时攻击，攻击力5倍"),
			"165":new FairyLeaderSkill(165, "弓连之力", "木属性、光属性同时攻击，所有精灵攻击力2.5倍"),
			"166":new FairyLeaderSkill(166, "霸·决", "火属性精灵攻击力2.5倍，受到火属性、暗属性伤害减少50%"),
			"167":new FairyLeaderSkill(167, "羞花绝貌", "受到水属性伤害减少50%；每次消除宝珠时，回复大量的生命值"),
			"168":new FairyLeaderSkill(168, "武·策", "精英类型精灵攻击力2.5倍"),
			"169":new FairyLeaderSkill(169, "燃·红莲之魂", "火属性精灵的攻击力和回复力变为2倍，HP变为1.35倍"),
			"170":new FairyLeaderSkill(170, "燃·七海之魂", "水属性精灵的攻击力和回复力变为2倍，HP变为1.35倍"),
			"171":new FairyLeaderSkill(171, "燃·生命之魂", "木属性精灵的攻击力和回复力变为2倍，HP变为1.35倍"),
			"172":new FairyLeaderSkill(172, "燃·雷电之魂", "光属性精灵的攻击力和回复力变为2倍，HP变为1.35倍"),
			"173":new FairyLeaderSkill(173, "燃·冥王之魂", "暗属性精灵的攻击力和回复力变为2倍，HP变为1.35倍"),
			"174":new FairyLeaderSkill(174, "天命·灵因", "神类型回复力2.5倍，受到光属性伤害减少30%"),
			"175":new FairyLeaderSkill(175, "天命·冥分", "神类型攻击力2.5倍，受到暗属性伤害减少30%"),
			"176":new FairyLeaderSkill(176, "曙光之子", "当生命值大于或等于80%时，光属性攻击力和回复力3.5倍"),
			"177":new FairyLeaderSkill(177, "堕落天使", "当生命值大于或等于80%时，暗属性精灵攻击力变为4倍")

			//exportData part end
		};
		
		public static const handlers:Object = {
			
			"1":{"type":1, "ext":{"buffId":5, "types":[FairysType.Fire], "rate":1.5}},
			"2":{"type":1, "ext":{"buffId":5, "types":[FairysType.Fire], "rate":2.0}},
			"3":{"type":1, "ext":{"buffId":5, "types":[FairysType.Water], "rate":1.5}},
			"4":{"type":1, "ext":{"buffId":5, "types":[FairysType.Water], "rate":2.0}},
			"5":{"type":1, "ext":{"buffId":5, "types":[FairysType.Wood], "rate":1.5}},
			"6":{"type":1, "ext":{"buffId":5, "types":[FairysType.Wood], "rate":2.0}},
			"7":{"type":1, "ext":{"buffId":5, "types":[FairysType.Light], "rate":1.5}},
			"8":{"type":1, "ext":{"buffId":5, "types":[FairysType.Light], "rate":2.0}},
			"9":{"type":1, "ext":{"buffId":5, "types":[FairysType.Dark], "rate":1.5}},
			"10":{"type":1, "ext":{"buffId":5, "types":[FairysType.Dark], "rate":2.0}},
			"11":{"type":1, "ext":{"buffId":4, "types":[], "rate":0.9, "forAll":true}},
			"12":{"type":1, "ext":{"buffId":4, "types":[FairysType.Fire], "rate":0.8}},
			"13":{"type":1, "ext":{"buffId":4, "types":[FairysType.Water], "rate":0.8}},
			"14":{"type":1, "ext":{"buffId":4, "types":[FairysType.Wood], "rate":0.8}},
			"15":{"type":1, "ext":{"buffId":4, "types":[FairysType.Light], "rate":0.8}},
			"16":{"type":1, "ext":{"buffId":4, "types":[FairysType.Dark], "rate":0.8}},
			"17":{"type":1, "ext":{"buffId":4, "types":[], "rate":0.8, "forAll":true}},
			"18":{"type":1, "ext":{"buffId":4, "types":[FairysType.Fire], "rate":0.5}},
			"19":{"type":1, "ext":{"buffId":4, "types":[FairysType.Water], "rate":0.5}},
			"20":{"type":1, "ext":{"buffId":4, "types":[FairysType.Wood], "rate":0.5}},
			"21":{"type":1, "ext":{"buffId":4, "types":[FairysType.Light], "rate":0.5}},
			"22":{"type":1, "ext":{"buffId":4, "types":[FairysType.Dark], "rate":0.5}},
			"23":{"type":1, "ext":{"buffId":6, "rate":3, "forAll":true}},
			"24":{"type":1, "ext":{"buffId":10, "rate":1}},
			"25":{"type":1, "ext":{"buffId":6, "rate":1.5, "forAll":true}},
			"26":{"type":1, "ext":{"buffId":10, "rate":1.5}},
			"27":{"type":1, "ext":{"buffId":10, "rate":3}},
			"28":{"type":1, "ext":{"buffId":5, "useTypes":[FairysUseType.Balance], "rate":2.5}},
			"29":{"type":1, "ext":{"buffId":7, "useTypes":[FairysUseType.Balance], "rate":2}},
			"30":{"type":1, "ext":{"buffId":8, "useTypes":[FairysUseType.Balance], "rate":2.5}},
			"31":{"type":1, "ext":{"buffId":5, "useTypes":[FairysUseType.God], "rate":2}},
			"32":{"type":1, "ext":{"buffId":7, "useTypes":[FairysUseType.Elite], "rate":2}},
			"33":{"type":1, "ext":{"buffId":5, "useTypes":[FairysUseType.Attack], "rate":2}},
			"34":{"type":1, "ext":{"buffId":5, "useTypes":[FairysUseType.PhysicalPower], "rate":2.5}},
			"35":{"type":1, "ext":{"buffId":5, "useTypes":[FairysUseType.PhysicalPower], "rate":2}},
			"36":{"type":[1, 1], "ext":[{"buffId":8, "useTypes":[FairysUseType.Balance], "rate":1.5}, {"buffId":7, "useTypes":[FairysUseType.Balance], "rate":1.5}]},
			"37":{"type":[1, 1, 1], "ext":[{"buffId":5, "useTypes":[FairysUseType.Balance], "rate":1.5}, {"buffId":8, "useTypes":[FairysUseType.Balance], "rate":1.5}, {"buffId":7, "useTypes":[FairysUseType.Balance], "rate":1.5}]},
			"38":{"type":1, "ext":{"buffId":7, "useTypes":[FairysUseType.PhysicalPower], "rate":1.5}},
			"39":{"type":1, "ext":{"buffId":7, "useTypes":[FairysUseType.PhysicalPower], "rate":2}},
			"40":{"type":1, "ext":{"buffId":5, "useTypes":[FairysUseType.Recover], "rate":2}},
			"41":{"type":1, "ext":{"buffId":5, "useTypes":[FairysUseType.Recover], "rate":2.5}},
			"42":{"type":1, "ext":{"buffId":9, "rate":0.8}},
			"43":{"type":1, "ext":{"buffId":9, "rate":2}},
			"44":{"type":1, "ext":{"buffId":1, "types":[FairysType.Fire, FairysType.Water, FairysType.Wood], "needNums":[3], "rates":[2.5]}},
			"45":{"type":1, "ext":{"buffId":5, "types":[FairysType.Water],  "rate":1.5}},
			"46":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Water], "rate":1.5}, {"buffId":8, "types":[FairysType.Water], "rate":1.5}]},
			"47":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Fire], "rate":1.5}, {"buffId":8, "types":[FairysType.Fire], "rate":1.5}]},
			"48":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Fire], "rate":2}, {"buffId":8, "types":[FairysType.Fire], "rate":2}]},
			"49":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Water], "rate":1.5}, {"buffId":8, "types":[FairysType.Water], "rate":1.5}]},
			"50":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Water], "rate":2}, {"buffId":8, "types":[FairysType.Water], "rate":2}]},
			"51":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Wood], "rate":1.5}, {"buffId":8, "types":[FairysType.Wood], "rate":1.5}]},
			"52":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Wood], "rate":2}, {"buffId":8, "types":[FairysType.Wood], "rate":2}]},
			"53":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Light], "rate":1.5}, {"buffId":8, "types":[FairysType.Light], "rate":1.5}]},
			"54":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Light], "rate":2}, {"buffId":8, "types":[FairysType.Light], "rate":2}]},
			"55":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Dark], "rate":1.5}, {"buffId":8, "types":[FairysType.Dark], "rate":1.5}]},
			"56":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Dark], "rate":2}, {"buffId":8, "types":[FairysType.Dark], "rate":2}]},
			"57":{"type":1, "ext":{"buffId":7, "types":[FairysType.Wood], "rate":2}},
			"58":{"type":[1, 1], "ext":[{"buffId":8, "types":[FairysType.Wood], "rate":2}, {"buffId":7, "types":[FairysType.Wood], "rate":2}]},
			"59":{"type":1, "ext":{"buffId":2, "hpRate":0.75, "atkRate":1.5, "types":[FairysType.Dark]}},
			"60":{"type":1, "ext":{"buffId":2, "hpRate":0.75, "atkRate":2.5, "types":[FairysType.Dark]}},
			"61":{"type":1, "ext":{"buffId":5, "types":[FairysType.Fire],  "rate":1.5}},
			"62":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Fire], "rate":1.5}, {"buffId":7, "types":[FairysType.Fire], "rate":1.5}]},
			"63":{"type":1, "ext":{"buffId":5, "types":[FairysType.Light], "rate":1.5}},
			"64":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Light], "rate":1.5}, {"buffId":7, "types":[FairysType.Light],  "rate":1.5}]},
			"65":{"type":1, "ext":{"buffId":1, "types":[FairysType.Fire, FairysType.Light, FairysType.Dark], "needNums":[3], "rates":[2.5]}},
			"66":{"type":1, "ext":{"buffId":7, "types":[FairysType.Water], "rate":2}},
			"67":{"type":1, "ext":{"buffId":7, "types":[FairysType.Water], "rate":2.5}},
			"68":{"type":1, "ext":{"buffId":10, "rate":5}},
			"69":{"type":1, "ext":{"buffId":4, "types":[FairysType.Dark], "rate":0.5}},
			"70":{"type":1, "ext":{"buffId":3, "rate":0.8}},
			"71":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Fire], "rate":1.5}, {"buffId":8, "types":[FairysType.Fire], "rate":1.5}]},
			"72":{"type":[1, 1, 1], "ext":[{"buffId":5, "types":[FairysType.Fire], "rate":1.5}, {"buffId":8, "types":[FairysType.Fire], "rate":1.5}, {"buffId":7, "types":[FairysType.Fire], "rate":1.5}]},
			"73":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Water], "rate":1.5}, {"buffId":8, "types":[FairysType.Water], "rate":1.5}]},
			"74":{"type":[1, 1, 1], "ext":[{"buffId":5, "types":[FairysType.Water], "rate":1.5}, {"buffId":8, "types":[FairysType.Water], "rate":1.5}, {"buffId":7, "types":[FairysType.Water], "rate":1.5}]},
			"75":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Wood], "rate":1.5}, {"buffId":8, "types":[FairysType.Wood], "rate":1.5}]},
			"76":{"type":[1, 1, 1], "ext":[{"buffId":5, "types":[FairysType.Wood], "rate":1.5}, {"buffId":8, "types":[FairysType.Wood], "rate":1.5}, {"buffId":7, "types":[FairysType.Wood], "rate":1.5}]},
			"77":{"type":1, "ext":{"buffId":1, "types":[FairysType.Water, FairysType.Wood, FairysType.Dark], "needNums":[3], "rates":[2.5]}},
			"78":{"type":1, "ext":{"buffId":7, "types":[FairysType.Wood], "rate":2.5}},
			"79":{"type":[1, 1], "ext":[{"buffId":5, "useTypes":[FairysUseType.Attack], "rate":1.5}, {"buffId":8, "useTypes":[FairysUseType.Attack], "rate":1.5}]},
			"80":{"type":1, "ext":{"buffId":2, "hpRate":0.3, "atkRate":2.5, "types":[1,2,3,4,5]}}	,
			"81":{"type":[1, 1], "ext":[{"buffId":8, "types":[FairysType.Fire], "rate":2}, {"buffId":7, "types":[FairysType.Fire], "rate":2}]},
			"82":{"type":[1, 1], "ext":[{"buffId":8, "types":[FairysType.Water], "rate":2}, {"buffId":7, "types":[FairysType.Water], "rate":2}]},
			"83":{"type":[1, 1], "ext":[{"buffId":8, "types":[FairysType.Wood], "rate":2}, {"buffId":7, "types":[FairysType.Wood], "rate":2}]},
			"84":{"type":1, "ext":{"buffId":11, "hpRate":0.5}},
			"85":{"type":1, "ext":{"buffId":2, "hpRate":0.8, "atkRate":3, "types":[1,2,3,4,5]}},
			
			"86":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Fire], "rate":2}, {"buffId":7, "types":[FairysType.Fire], "rate":2}]},
			"87":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Water], "rate":2}, {"buffId":7, "types":[FairysType.Water], "rate":2}]},
			"88":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Wood], "rate":2}, {"buffId":7, "types":[FairysType.Wood], "rate":2}]},
			"89":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Light], "rate":2}, {"buffId":7, "types":[FairysType.Light], "rate":2}]},
			"90":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Dark], "rate":2}, {"buffId":7, "types":[FairysType.Dark], "rate":2}]},
			"91":{"type": 1, "ext":{"buffId":5, "types":[FairysType.Light], "useTypes":[FairysUseType.God], "rate":2.5}},
			
			"92":{"type":1, "ext":{"buffId":6, "rate":2.5, "types":[FairysType.Fire]}},
			"93":{"type":1, "ext":{"buffId":6, "rate":3, "types":[FairysType.Fire]}},
			"94":{"type":1, "ext":{"buffId":6, "rate":2.5, "types":[FairysType.Water]}},
			"95":{"type":1, "ext":{"buffId":6, "rate":3, "types":[FairysType.Water]}},
			"96":{"type":1, "ext":{"buffId":6, "rate":2.5, "types":[FairysType.Wood]}},
			"97":{"type":1, "ext":{"buffId":6, "rate":3, "types":[FairysType.Wood]}},
			"98":{"type":1, "ext":{"buffId":6, "rate":2.5, "types":[FairysType.Light]}},
			"99":{"type":1, "ext":{"buffId":6, "rate":3, "types":[FairysType.Light]}},
			"100":{"type":1, "ext":{"buffId":6, "rate":2.5, "types":[FairysType.Dark]}},
			"101":{"type":1, "ext":{"buffId":6, "rate":3, "types":[FairysType.Dark]}},
			
			"102":{"type":1, "ext":{"buffId":12, "hpRate":0.8, "atkRate":2.8, "types":[FairysType.Fire]}},
			"103":{"type":1, "ext":{"buffId":5, "types":[FairysType.Water], "rate":2.5}},
			"104":{"type":1, "ext":{"buffId":5, "types":[FairysType.Wood], "rate":2.5}},
			
			"105":{"type":1, "ext":{"buffId":5, "types":[FairysType.Light], "rate":2.5}},
			"106":{"type":1, "ext":{"buffId":12, "hpRate":0.8, "atkRate":3, "types":[FairysType.Dark]}},
			
			"107":{"type":1, "ext":{"buffId":4, "types":[FairysType.Fire], "rate":0.5}},
			"108":{"type":1, "ext":{"buffId":4, "types":[FairysType.Water], "rate":0.5}},
			"109":{"type":1, "ext":{"buffId":4, "types":[FairysType.Wood], "rate":0.5}},
			"110":{"type":1, "ext":{"buffId":4, "types":[FairysType.Light], "rate":0.5}},
			"111":{"type":1, "ext":{"buffId":4, "types":[FairysType.Dark], "rate":0.5}},
			"112":{"type":1, "ext":{"buffId":13, "combos":[3], "rates":[2]}},
			
			"113":{"type":[1, 1], "ext":[{"buffId":7, "types":[FairysType.Light], "rate":1.3}, {"buffId":5, "types":[FairysType.Light], "rate":2}]},
			"114":{"type":[1, 1], "ext":[{"buffId":7, "types":[FairysType.Dark], "rate":1.3}, {"buffId":5, "types":[FairysType.Dark], "rate":2}]},
			
			"115":{"type":[1, 1], "ext":[{"buffId":7, "types":[FairysType.Fire], "rate":1.3}, {"buffId":5, "types":[FairysType.Fire], "rate":2}]},
			"116":{"type":[1, 1], "ext":[{"buffId":7, "types":[FairysType.Water], "rate":1.3}, {"buffId":5, "types":[FairysType.Water], "rate":2}]},
			"117":{"type":[1, 1], "ext":[{"buffId":7, "types":[FairysType.Wood],  "rate":1.3}, {"buffId":5, "types":[FairysType.Wood], "rate":2}]},
		
			"118":{"type":[1, 1], "ext":[{"buffId":7, "types":[FairysType.Fire], "rate":1.3}, {"buffId":5, "types":[FairysType.Fire], "rate":3}]},
			"119":{"type":[1, 1], "ext":[{"buffId":7, "types":[FairysType.Water],  "rate":1.3}, {"buffId":5, "types":[FairysType.Water], "rate":3}]},
			"120":{"type":[1, 1], "ext":[{"buffId":7, "types":[FairysType.Wood], "rate":1.3}, {"buffId":5, "types":[FairysType.Wood], "rate":3}]},
			"121":{"type":[1, 1], "ext":[{"buffId":7, "types":[FairysType.Light], "rate":1.3}, {"buffId":5, "types":[FairysType.Light], "rate":3}]},
			"122":{"type":[1, 1], "ext":[{"buffId":7, "types":[FairysType.Dark], "rate":1.3}, {"buffId":5, "types":[FairysType.Dark], "rate":3}]},
			"123":{"type":1, "ext":{"buffId":6,  "useTypes":[FairysUseType.God], "rate":3}},
			"124":{"type":1, "ext":{"buffId":12, "hpRate":0.8, "atkRate":3, "types":[FairysType.Fire]}},

			"125":{"type":[1, 1], "ext":[{"buffId":12, "types":[FairysType.Light], "hpRate":0.5, "atkRate":2.5 }, {"buffId":14, "types":[FairysType.Light], "hpRate":0.5, "recoverRate":2.5}]},
			
			"126":{"type": 1, "ext":{"buffId":5, "useTypes":[FairysUseType.Elite], "rate":3}},
			"127":{"type":[1, 1], "ext":[{"buffId":7, "types":[FairysType.Water], "rate":1.5}, {"buffId":5, "types":[FairysType.Water], "rate":2}]},
			"128":{"type":[1, 1], "ext":[{"buffId":7, "types":[FairysType.Wood], "rate":1.5 }, {"buffId":5, "types":[FairysType.Wood], "rate":2}]},
			"129":{"type":[1, 1], "ext":[{"buffId":12, "types":[FairysType.Light], "hpRate":0.5, "atkRate":3.5 }, {"buffId":14, "types":[FairysType.Light], "hpRate":0.5, "recoverRate":1.5}]},
			"130":{"type":[1, 1], "ext":[{"buffId":12, "types":[FairysType.Dark], "hpRate":0.5, "atkRate":3.5 }, {"buffId":14, "types":[FairysType.Dark], "hpRate":0.5, "recoverRate":1.5}]},
		
			"131":{"type":[1, 1], "ext":[{"buffId":7, "types":[FairysType.Fire], "useTypes":[FairysUseType.PhysicalPower], "rate":2}, {"buffId":5, "types":[FairysType.Fire], "useTypes":[FairysUseType.PhysicalPower], "rate":2}]},
			"132":{"type":[1, 1], "ext":[{"buffId":7, "types":[FairysType.Water], "useTypes":[FairysUseType.Recover], "rate":2}, {"buffId":5, "types":[FairysType.Water], "useTypes":[FairysUseType.Recover], "rate":2}]},
			"133":{"type":[1, 1], "ext":[{"buffId":7, "types":[FairysType.Wood], "useTypes":[FairysUseType.Balance], "rate":2}, {"buffId":5, "types":[FairysType.Wood], "useTypes":[FairysUseType.Balance], "rate":2}]},
			"134":{"type":[1, 1], "ext":[{"buffId":7, "types":[FairysType.Light], "useTypes":[FairysUseType.Attack], "rate":2}, {"buffId":5, "types":[FairysType.Light], "useTypes":[FairysUseType.Attack], "rate":2}]},
			"135":{"type":[1, 1], "ext":[{"buffId":7, "types":[FairysType.Dark], "useTypes":[FairysUseType.Elite], "rate":2}, {"buffId":5, "types":[FairysType.Dark], "useTypes":[FairysUseType.Elite], "rate":2}]},
			"136":{"type":1, "ext":{"buffId":4, "types":[FairysType.Fire], "rate":0.4}},
			"137":{"type":1, "ext":{"buffId":4, "types":[FairysType.Wood], "rate":0.4}},
			"138":{"type":1, "ext":{"buffId":4, "types":[FairysType.Water], "rate":0.4}},
			
			"139":{"type":1, "ext":{"buffId":4, "types":[FairysType.Light], "rate":0.4}},
			"140":{"type":1, "ext":{"buffId":4, "types":[FairysType.Dark], "rate":0.4}},
			
			"141":{"type":[1, 1], "ext":[{"buffId":5, "useTypes":[FairysUseType.Recover], "rate":2}, {"buffId":7, "useTypes":[FairysUseType.Recover], "rate":2}]},
			"142":{"type":[1, 1], "ext":[{"buffId":5, "useTypes":[FairysUseType.PhysicalPower], "rate":2}, {"buffId":8, "useTypes":[FairysUseType.PhysicalPower], "rate":2}]},
			"143":{"type":[1, 1], "ext":[{"buffId":5, "useTypes":[FairysUseType.Attack], "rate":2}, {"buffId":8, "useTypes":[FairysUseType.Attack], "rate":2}]},
			
			"144":{"type":[1, 1], "ext":[{"buffId":7, "types":[FairysType.Wood], "rate":1.5}, {"buffId":5, "types":[FairysType.Wood], "rate":2}]},
			"145":{"type":[1, 1], "ext":[{"buffId":7, "types":[FairysType.Light], "rate":1.5}, {"buffId":5, "types":[FairysType.Light], "rate":2}]},
			"146":{"type":[1, 1], "ext":[{"buffId":7, "types":[FairysType.Water], "rate":1.5}, {"buffId":5, "types":[FairysType.Water], "rate":2}]},
			"147":{"type":[1, 1], "ext":[{"buffId":5, "useTypes":[FairysUseType.Recover], "rate":2.5}, {"buffId":7, "useTypes":[FairysUseType.Recover], "rate":2}]},
			"148":{"type":[1, 1], "ext":[{"buffId":5, "useTypes":[FairysUseType.PhysicalPower], "rate":2.5}, {"buffId":8, "useTypes":[FairysUseType.PhysicalPower], "rate":2}]},
			"149":{"type":[1, 1], "ext":[{"buffId":5, "useTypes":[FairysUseType.Attack], "rate":2.5}, {"buffId":8, "useTypes":[FairysUseType.Attack], "rate":2}]},
			
			"150":{"type":[1, 1], "ext":[{"buffId":5, "useTypes":[FairysUseType.Attack], "rate":2}, {"buffId":8, "useTypes":[FairysUseType.Attack], "rate":2}]},
			"151":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Fire, FairysType.Dark], "rate":2.5}, {"buffId":8, "types":[FairysType.Fire, FairysType.Dark], "rate":2.5}]},
			
			"152":{"type":[1, 1, 1], "ext":[{"buffId":5, "useTypes":[FairysUseType.Balance], "rate":1.5}, {"buffId":8, "useTypes":[FairysUseType.Balance], "rate":1.5}, {"buffId":7, "useTypes":[FairysUseType.Balance], "rate":1.5}]},
			"153":{"type":[1, 1], "ext":[{"buffId":5, "useTypes":[FairysUseType.Elite], "rate":2}, {"buffId":8, "useTypes":[FairysUseType.Elite], "rate":2}]},
			
			"154":{"type":1, "ext":{"buffId":4, "types":[FairysType.Water], "rate":0.5}},
			"155":{"type":1, "ext":{"buffId":12, "useTypes":[FairysUseType.Recover], "hpRate":0.5, "atkRate":2.5 }},
			"156":{"type":1, "ext":{"buffId":12, "useTypes":[FairysUseType.PhysicalPower], "hpRate":0.5, "atkRate":2.5 }},
			"157":{"type":1, "ext":{"buffId":12, "useTypes":[FairysUseType.Elite], "hpRate":0.5, "atkRate":2.5 }},
			"158":{"type":1, "ext":{"buffId":12, "useTypes":[FairysUseType.Attack], "hpRate":0.5, "atkRate":2.5 }},
			"159":{"type":1, "ext":{"buffId":4, "types":[FairysType.Light], "rate":0.5}},
			
			"160":{"type":[1, 1, 1], "ext":[{"buffId":1, "types":[FairysType.Fire, FairysType.Wood, FairysType.Dark], "needNums":[3], "rates":[3.5]}, {"buffId":8, "types":[FairysType.Fire], "rate":1.3}, {"buffId":7, "types":[FairysType.Fire], "rate":1.3}]},
			"161":{"type":[1, 1, 1], "ext":[{"buffId":1, "types":[FairysType.Water, FairysType.Fire, FairysType.Light], "needNums":[3], "rates":[3.5]}, {"buffId":8, "types":[FairysType.Water], "rate":1.3}, {"buffId":7, "types":[FairysType.Water], "rate":1.3}]},
			"162":{"type":[1, 1, 1], "ext":[{"buffId":1, "types":[FairysType.Wood, FairysType.Light, FairysType.Dark], "needNums":[3], "rates":[3.5]}, {"buffId":8, "types":[FairysType.Wood], "rate":1.3}, {"buffId":7, "types":[FairysType.Wood], "rate":1.3}]},
			"163":{"type":[1, 1, 1], "ext":[{"buffId":1, "types":[FairysType.Fire, FairysType.Water, FairysType.Wood, FairysType.Light, FairysType.Dark], "needNums":[4], "rates":[4]}, {"buffId":8, "types":[FairysType.Light], "rate":1.3}, {"buffId":7, "types":[FairysType.Light], "rate":1.3}]},
			"164":{"type":[1, 1, 1], "ext":[{"buffId":1, "types":[FairysType.Fire, FairysType.Water, FairysType.Wood, FairysType.Light, FairysType.Dark], "needNums":[5], "rates":[5]}, {"buffId":8, "types":[FairysType.Dark], "rate":1.3}, {"buffId":7, "types":[FairysType.Dark], "rate":1.3}]},
		
			"165":{"type":1, "ext":{"buffId":1, "types":[FairysType.Light, FairysType.Wood], "needNums":[2], "rates":[2.5]}},
			"166":{"type":[1, 1], "ext":[{"buffId":5, "types":[FairysType.Fire], "rate":2.5}, {"buffId":4, "types":[FairysType.Fire, FairysType.Dark], "rate":0.5}]},
			"167":{"type":[1, 1], "ext":[{"buffId":10, "rate":3}, {"buffId":4, "types":[FairysType.Water], "rate":0.5}]},
			"168":{"type":1, "ext":{"buffId":5, "useTypes":[FairysUseType.Elite], "rate":2.5}},
			
			
			"169":{"type":[1, 1, 1], "ext":[{"buffId":5, "types":[FairysType.Fire], "rate":2}, {"buffId":8, "types":[FairysType.Fire], "rate":2}, {"buffId":7, "types":[FairysType.Fire], "rate":1.35}]},
			"170":{"type":[1, 1, 1], "ext":[{"buffId":5, "types":[FairysType.Water], "rate":2}, {"buffId":8, "types":[FairysType.Water], "rate":2}, {"buffId":7, "types":[FairysType.Water], "rate":1.35}]},
			"171":{"type":[1, 1, 1], "ext":[{"buffId":5, "types":[FairysType.Wood], "rate":2}, {"buffId":8, "types":[FairysType.Wood], "rate":2}, {"buffId":7, "types":[FairysType.Wood], "rate":1.35}]},
			"172":{"type":[1, 1, 1], "ext":[{"buffId":5, "types":[FairysType.Light], "rate":2}, {"buffId":8, "types":[FairysType.Light], "rate":2}, {"buffId":7, "types":[FairysType.Light], "rate":1.35}]},
			"173":{"type":[1, 1, 1], "ext":[{"buffId":5, "types":[FairysType.Dark], "rate":2}, {"buffId":8, "types":[FairysType.Dark], "rate":2}, {"buffId":7, "types":[FairysType.Dark], "rate":1.35}]},

			"174":{"type":[1, 1], "ext":[{"buffId":8, "useTypes":[FairysUseType.God], "rate":2.5}, {"buffId":4, "types":[FairysType.Light], "rate":0.7}]},
			"175":{"type":[1, 1], "ext":[{"buffId":5, "useTypes":[FairysUseType.God], "rate":2.5}, {"buffId":4, "types":[FairysType.Dark], "rate":0.7}]},
			"176":{"type":[1, 1], "ext":[{"buffId":12, "types":[FairysType.Light], "hpRate":0.5, "atkRate":3.5 }, {"buffId":14, "types":[FairysType.Light], "hpRate":0.5, "recoverRate":3.5}]},
			"177":{"type":1, "ext":{"buffId":12, "hpRate":0.8, "atkRate":4, "types":[FairysType.Dark]}}
		};
		
		public static const leaderBuffClassMap:Object = {
			//当几个属性的宝珠一起攻击生效时，攻击倍率加成, "types":限定珠子类型数组 ，"needNums":[4,3]达到种类数量触发数（请从大到小），"rates":[5,4]触发倍率对应种类数量（从大到小）, 
			"1":"mmo.fairybattle.buff.leaderbuff.LeaderBuffLimitClearAtkUp",
			//当血量低于某个比例攻击加成  "hpRate":低于血的比例, "atkRate":攻击加成倍率 "types":属性类型数组 "useTypes":攻击类型数组
			"2":"mmo.fairybattle.buff.leaderbuff.LeaderBuffLowHpAtkUp",
			//满血的时候减伤  "rate"：满血时减少百分之多少的伤害
			"3":"mmo.fairybattle.buff.leaderbuff.LeaderBuffFullHpDefenseUp",
			//某属性或某攻击类型有减伤加成 "types":属性（数组） "useTypes":使用类型（数组）"rate":是减伤后的比例，如果是减伤20%那就是0.8
			"4":"mmo.fairybattle.buff.leaderbuff.LeaderBuffTypeDefUp",
			//某属性或某攻击类型有攻击倍率加成 rate":加成倍率 "types":属性（数组） "useTypes":使用类型（数组）
			"5":"mmo.fairybattle.buff.leaderbuff.LeaderBuffAtkUp",
			//满血时候攻击倍率加成 {"rate":加成倍率 "types":属性（数组） "useTypes":使用类型（数组） "forAll":是否不限定使用类型和属性（布尔型）}
			"6":"mmo.fairybattle.buff.leaderbuff.LeaderBuffFullHpAtkUp",
			//某属性或某攻击类型血量增加 "rate":加成倍率 "types":属性（数组） "useTypes":使用类型（数组）
			"7":"mmo.fairybattle.buff.leaderbuff.LeaderBuffMaxHpUp",
			//某属性或某攻击类型有回复力倍率加成 "rate":加成倍率 "types":属性（数组） "useTypes":使用类型（数组）
			"8":"mmo.fairybattle.buff.leaderbuff.LeaderBuffRecoverUp",
			//额外一次全体攻击，每次消除宝珠成功，造成伤害为buff持有者"rate"倍攻击力的
			"9":"mmo.fairybattle.buff.leaderbuff.LeaderBuffExAtk",
			//额外一次回血加成,每次消除宝成功，回复量为buff持有者"rate"倍回复力
			"10":"mmo.fairybattle.buff.leaderbuff.LeaderBuffExRecover",
			//根性 "hpRate":大于某个血量比例触发
			"11":"mmo.fairybattle.buff.leaderbuff.LeaderBuffGuts",
			//当血量高于某个比例攻击加成  "hpRate":低于血的比例, "atkRate":攻击加成倍率 "types":属性类型数组 属性类型数组 "useTypes":攻击类型数组
			"12":"mmo.fairybattle.buff.leaderbuff.LeaderBuffHighHpAtkUp",
			//当高于某个COMBO开始有攻击加成，支持多段不同倍率  "rates":攻击加成的倍率, "combos"：COMBO数
			"13":"mmo.fairybattle.buff.leaderbuff.LeaderBuffComboAtkUp",
			//当血量高于某个比例恢复力加成  "hpRate":低于血的比例, "recoverRate":攻击加成倍率 "types":属性类型数组 "useTypes":攻击类型数组
			"14":"mmo.fairybattle.buff.leaderbuff.LeaderBuffHighHpRecoverUp",
			//当血量低于某个比例恢复力加成  "hpRate":低于血的比例, "recoverRate":攻击加成倍率 "types":属性类型数组"useTypes":攻击类型数组
			"15":"mmo.fairybattle.buff.leaderbuff.LeaderBuffLowHpRecoverUp"
		}
		
		public static const handlerTypes:Object = {
			"0":"",
			//buff类型的队长技
			"1":"mmo.fairybattle.skill.leaderskillHandler.LeaderSkillBuffHandler"
		}
	}
}
