package mmo.materialdata.fairy
{
	import mmo.framework.domain.fairy.FairyMainSkill;
	import mmo.framework.domain.fairy.FairyMainSkillLevel;
	import mmo.framework.domain.fairy.FairysType;
	
	public class FairyMainSkillsData
	{
		public function FairyMainSkillsData()
		{
		}
		/**
		 * 扩展字段，主要用于处理器的配置，
		 * （因静态变量必须先定义在前才能被后面静态变量引用，特意写在前面）
		 */		
		public static const handlers:Object = {
			"0":{"type":0, "ext":{}},
			"1":{"type":1, "ext":{"type":FairysType.Fire, "rate":5}},
			"2":{"type":1, "ext":{"type":FairysType.Fire, "rate":30}},
			"3":{"type":1, "ext":{"type":FairysType.Water, "rate":5}},
			"4":{"type":1, "ext":{"type":FairysType.Water, "rate":30}},
			"5":{"type":1, "ext":{"type":FairysType.Wood, "rate":5}},
			"6":{"type":1, "ext":{"type":FairysType.Wood, "rate":30}},
			"7":{"type":1, "ext":{"type":FairysType.Light, "rate":5}},
			"8":{"type":1, "ext":{"type":FairysType.Light, "rate":30}},
			"9":{"type":1, "ext":{"type":FairysType.Dark, "rate":5}},
			"10":{"type":1, "ext":{"type":FairysType.Dark, "rate":30}},
			"11":{"type":2, "ext":{"beforeType":6, "afterType":FairysType.Fire}},
			"12":{"type":2, "ext":{"beforeType":FairysType.Fire, "afterType":6}},
			"13":{"type":3, "ext":{}},
			"14":{"type":2, "ext":{"beforeType":FairysType.Dark, "afterType":6}},
			"15":{"type":2, "ext":{"beforeType":6, "afterType":FairysType.Dark}},
			"16":{"type":4, "ext":{"value":300}},
			"17":{"type":11, "ext":{"friendBuffId":1}},
			"18":{"type":0, "ext":{}},
			"19":{"type":4, "ext":{"value":500}},
			"20":{"type":1, "ext":{"type":FairysType.Fire, "rate":15}},
			"21":{"type":1, "ext":{"type":FairysType.Water, "rate":15}},
			"22":{"type":1, "ext":{"type":FairysType.Wood, "rate":15}},
			"23":{"type":1, "ext":{"type":FairysType.Light, "rate":15}},
			"24":{"type":1, "ext":{"type":FairysType.Dark, "rate":15}},
			"25":{"type":7, "ext":{"rate":10, "recoverRate":1}},
			"26":{"type":6, "ext":{"rate":1}},
			"27":{"type":[2, 2], "ext":[{"beforeType":6, "afterType":FairysType.Light},{"beforeType":FairysType.Dark, "afterType":FairysType.Light}]},
			"28":{"type":8, "ext":{"rate":0.3}},
			"29":{"type":9, "ext":{"type":FairysType.Fire, "rate":50}},
			"30":{"type":1, "ext":{"type":FairysType.Light, "rate":40}},
			"31":{"type":4, "ext":{"value":2000}},
			"32":{"type":5, "ext":{"addTurn":3}},
			"33":{"type":2, "ext":{"beforeType":FairysType.Water, "afterType":6}},
			"34":{"type":10, "ext":{"rate":5}},
			"35":{"type":10, "ext":{"rate":10}},
			"36":{"type":[2, 2], "ext":[{"beforeType":FairysType.Light, "afterType":6},{"beforeType":6, "afterType":FairysType.Dark}]},
			"37":{"type":2, "ext":{"beforeType":FairysType.Fire, "afterType":6}},
			"38":{"type":2, "ext":{"beforeType":FairysType.Water, "afterType":FairysType.Fire}},
			"39":{"type":2, "ext":{"beforeType":FairysType.Wood, "afterType":FairysType.Water}},
			"40":{"type":2, "ext":{"beforeType":FairysType.Fire, "afterType":FairysType.Wood}},
			"41":{"type":2, "ext":{"beforeType":FairysType.Dark, "afterType":FairysType.Light}},
			"42":{"type":2, "ext":{"beforeType":FairysType.Light, "afterType":FairysType.Dark}},
			"43":{"type":1, "ext":{"type":FairysType.Fire, "rate":10}},
			"44":{"type":1, "ext":{"type":FairysType.Water, "rate":10}},
			"45":{"type":2, "ext":{"beforeType":6, "afterType":FairysType.Water}},
			"46":{"type":2, "ext":{"beforeType":6, "afterType":FairysType.Wood}},
			"47":{"type":1, "ext":{"type":FairysType.Wood, "rate":10}},
			"48":{"type":2, "ext":{"beforeType":6, "afterType":FairysType.Fire}},
			"49":{"type":2, "ext":{"beforeType":6, "afterType":FairysType.Light}},
			"50":{"type":2, "ext":{"beforeType":6, "afterType":FairysType.Dark}},
			"51":{"type":12, "ext":{"damage":5000, "directDamage":true, "type":FairysType.Wood}},
			"52":{"type":12, "ext":{"damage":505, "directDamage":false, "type":FairysType.Wood}},
			"53":{"type":7, "ext":{"rate":6, "recoverRate":0.5}},
			"54":{"type":11, "ext":{"friendBuffId":2}},
			"55":{"type":11, "ext":{"friendBuffId":3}},
			"56":{"type":11, "ext":{"friendBuffId":4}},
			"57":{"type":11, "ext":{"friendBuffId":5}},
			"58":{"type":11, "ext":{"friendBuffId":6}},
			"59":{"type":1, "ext":{"type":FairysType.Light, "rate":10}},
			"60":{"type":11, "ext":{"friendBuffId":7}},
			"61":{"type":14, "ext":{"type":FairysType.Fire}},
			"62":{"type":13, "ext":{"enemyBuffId":1}},
			"63":{"type":1, "ext":{"type":FairysType.Dark, "rate":10}},
			"64":{"type":14, "ext":{"type":FairysType.Water}},
			"65":{"type":11, "ext":{"friendBuffId":8}},
			"66":{"type":14, "ext":{"type":FairysType.Wood}},
			"67":{"type":13, "ext":{"enemyBuffId":2}},
			"68":{"type":13, "ext":{"enemyBuffId":3}},
			"69":{"type":9, "ext":{"type":FairysType.Dark, "rate":50}},
			"70":{"type":14, "ext":{"type":FairysType.Light}},
			"71":{"type":13, "ext":{"enemyBuffId":5}},
			"72":{"type":5, "ext":{"addTurn":5}},
			"73":{"type":14, "ext":{"type":FairysType.Dark}},	
			"74":{"type":11, "ext":{"friendBuffId":9}},
			"75":{"type":2, "ext":{"beforeType":FairysType.Light, "afterType":6}},
			"76":{"type":[2, 2], "ext":[{"beforeType":6, "afterType":FairysType.Dark},{"beforeType":FairysType.Light, "afterType":6}]},
			"77":{"type":12, "ext":{"damage":7777, "directDamage":true, "type":FairysType.Fire}},
			"78":{"type":2, "ext":{"beforeType":FairysType.Wood, "afterType":6}},
			"79":{"type":[2, 2], "ext":[{"beforeType":FairysType.Light, "afterType":FairysType.Dark},{"beforeType":FairysType.Water, "afterType":FairysType.Dark}]},
			"80":{"type":[2, 2, 2, 2, 2, 2], "ext":[{"beforeType":FairysType.Fire, "afterType":FairysType.Light},{"beforeType":FairysType.Water, "afterType":FairysType.Light},{"beforeType":FairysType.Wood, "afterType":FairysType.Light},{"beforeType":FairysType.Dark, "afterType":FairysType.Light},{"beforeType":6, "afterType":FairysType.Light},{"beforeType":7, "afterType":FairysType.Light}]},
			"81":{"type":[2, 2], "ext":[{"beforeType":FairysType.Water, "afterType":FairysType.Fire},{"beforeType":6, "afterType":FairysType.Fire}]},
			"82":{"type":[2, 2], "ext":[{"beforeType":FairysType.Wood, "afterType":FairysType.Water},{"beforeType":6, "afterType":FairysType.Water}]},
			"83":{"type":[2, 2], "ext":[{"beforeType":FairysType.Fire, "afterType":FairysType.Wood},{"beforeType":6, "afterType":FairysType.Wood}]},
			"84":{"type":[2, 2], "ext":[{"beforeType":FairysType.Dark, "afterType":FairysType.Light},{"beforeType":6, "afterType":FairysType.Light}]},
			"85":{"type":[2, 2], "ext":[{"beforeType":FairysType.Light, "afterType":FairysType.Dark},{"beforeType":6, "afterType":FairysType.Dark}]},
			"86":{"type":8, "ext":{"rate":0.35}},
			
			"87":{"type":[2, 2], "ext":[{"beforeType":FairysType.Wood, "afterType":FairysType.Fire},{"beforeType":6, "afterType":FairysType.Wood}]},
			"88":{"type":[2, 2], "ext":[{"beforeType":FairysType.Fire, "afterType":FairysType.Water},{"beforeType":6, "afterType":FairysType.Fire}]},
			"89":{"type":[2, 2], "ext":[{"beforeType":FairysType.Water, "afterType":FairysType.Wood},{"beforeType":6, "afterType":FairysType.Water}]},
			"90":{"type":[2, 2], "ext":[{"beforeType":FairysType.Dark, "afterType":FairysType.Light},{"beforeType":6, "afterType":FairysType.Dark}]},
			"91":{"type":[2, 2], "ext":[{"beforeType":FairysType.Light, "afterType":FairysType.Dark},{"beforeType":6, "afterType":FairysType.Light}]},
			
			"92":{"type":2, "ext":{"beforeType":FairysType.Light, "afterType":FairysType.Fire}},
			"93":{"type":2, "ext":{"beforeType":FairysType.Dark, "afterType":FairysType.Water}},
			"94":{"type":2, "ext":{"beforeType":FairysType.Water, "afterType":FairysType.Wood}},
			"95":{"type":2, "ext":{"beforeType":FairysType.Wood, "afterType":FairysType.Light}},
			"96":{"type":2, "ext":{"beforeType":FairysType.Fire, "afterType":FairysType.Dark}},
			
			"97":{"type":11, "ext":{"friendBuffId":10}},
			"98":{"type":[2, 2], "ext":[{"beforeType":FairysType.Fire, "afterType":FairysType.Water},{"beforeType":6, "afterType":FairysType.Wood}]},
			"99":{"type":11, "ext":{"friendBuffId":11}},
			
			"100":{"type":[9, 14], "ext":[{"type":FairysType.Light, "rate":20},{"type":FairysType.Light}]},
			"101":{"type":[9, 14], "ext":[{"type":FairysType.Dark, "rate":20},{"type":FairysType.Dark}]},
			
			"102":{"type":[2, 2], "ext":[{"beforeType":FairysType.Wood, "afterType":FairysType.Fire},{"beforeType":6, "afterType":FairysType.Wood}]},
			"103":{"type":[2, 2], "ext":[{"beforeType":FairysType.Fire, "afterType":FairysType.Water},{"beforeType":6, "afterType":FairysType.Fire}]},
			"104":{"type":[2, 2], "ext":[{"beforeType":FairysType.Water, "afterType":FairysType.Wood},{"beforeType":6, "afterType":FairysType.Water}]},
			"105":{"type":[2, 2], "ext":[{"beforeType":FairysType.Dark, "afterType":FairysType.Light},{"beforeType":6, "afterType":FairysType.Dark}]},
			"106":{"type":[2, 2], "ext":[{"beforeType":FairysType.Light, "afterType":FairysType.Dark},{"beforeType":6, "afterType":FairysType.Light}]},
			"107":{"type":11, "ext":{"friendBuffId":12}},
			
			"108":{"type":15, "ext":{"rate":6}},
			"109":{"type":[1, 5], "ext":[{"type":FairysType.Dark, "rate":10},{"addTurn":1}]},
			
			"110":{"type":[2, 2], "ext":[{"beforeType":FairysType.Wood, "afterType":6},{"beforeType":FairysType.Light, "afterType":6}]},
			"111":{"type":[2, 2], "ext":[{"beforeType":FairysType.Fire, "afterType":6},{"beforeType":FairysType.Dark, "afterType":6}]},
			"112":{"type":[2, 2], "ext":[{"beforeType":FairysType.Water, "afterType":6},{"beforeType":FairysType.Light, "afterType":6}]},
			
			"113":{"type":[2, 5], "ext":[{"beforeType":FairysType.Water, "afterType":FairysType.Fire},{"addTurn":1}]},
			"114":{"type":11, "ext":{"friendBuffId":13}},
			"115":{"type":[2, 5], "ext":[{"beforeType":FairysType.Dark, "afterType":FairysType.Wood},{"addTurn":1}]},
			"116":{"type":11, "ext":{"friendBuffId":14}},
			"117":{"type":11, "ext":{"friendBuffId":15}},
			"118":{"type":8, "ext":{"rate":0.2}},
			"119":{"type":[4, 2], "ext":[{"value":3000},{"beforeType":6, "afterType":FairysType.Fire}]},
		
			"120":{"type":[14, 14], "ext":[{"type":FairysType.Wood},{"type":FairysType.Light}]},
			
			"121":{"type":[14, 5], "ext":[{"type":FairysType.Fire},{"addTurn":1}]},
			"122":{"type":7, "ext":{"rate":20, "recoverRate":0.5}},
			"123":{"type":7, "ext":{"rate":20, "recoverRate":0.5}},
			"124":{"type":[9, 2], "ext":[{"type":FairysType.Light, "rate":80},{"beforeType":FairysType.Wood, "afterType":FairysType.Light}]},
			"125":{"type":[2, 5], "ext":[{"beforeType":FairysType.Water, "afterType":FairysType.Dark},{"addTurn":1}]},
		
			"126":{"type":[11, 5], "ext":[{"friendBuffId":16},{"addTurn":1}]},
			"127":{"type":[11, 5], "ext":[{"friendBuffId":17},{"addTurn":1}]},	
			"128":{"type":[11, 2], "ext":[{"friendBuffId":18},{"beforeType":6, "afterType":FairysType.Light}]},
			
			"129":{"type":11, "ext":{"friendBuffId":22}},
			"130":{"type":[11, 5], "ext":[{"friendBuffId":19},{"addTurn":1}]},
			"131":{"type":[11, 5], "ext":[{"friendBuffId":20},{"addTurn":1}]},	
			"132":{"type":[11, 2], "ext":[{"friendBuffId":21},{"beforeType":6, "afterType":FairysType.Light}]},
			
			"133":{"type":[2, 2], "ext":[{"beforeType":FairysType.Dark, "afterType":FairysType.Light},{"beforeType":6, "afterType":FairysType.Dark}]},
			"134":{"type":16, "ext":{"orderTypes":[FairysType.Fire, FairysType.Dark]}},
			
			"135":{"type":[11, 5], "ext":[{"friendBuffId":23},{"addTurn":1}]},	
			"136":{"type":[11, 2], "ext":[{"friendBuffId":24},{"beforeType":6, "afterType":FairysType.Dark}]},
	
			"137":{"type":11, "ext":{"friendBuffId":25}},
			"138":{"type":[14, 6], "ext":[{"type":FairysType.Water},{"rate":0.2}]},
			
			"139":{"type":[2, 2], "ext":[{"beforeType":FairysType.Water, "afterType":FairysType.Fire},{"beforeType":6, "afterType":FairysType.Water}]},
			"140":{"type":[2, 2], "ext":[{"beforeType":FairysType.Light, "afterType":FairysType.Dark},{"beforeType":6, "afterType":FairysType.Light}]},
			"141":{"type":[2, 2], "ext":[{"beforeType":FairysType.Dark, "afterType":FairysType.Light},{"beforeType":6, "afterType":FairysType.Dark}]},
			"142":{"type":11, "ext":{"friendBuffId":26}},
		
			"143":{"type":16, "ext":{"orderTypes":[FairysType.Fire, FairysType.Wood, FairysType.Dark]}},
			"144":{"type":16, "ext":{"orderTypes":[FairysType.Water, FairysType.Fire, FairysType.Light]}},
			"145":{"type":16, "ext":{"orderTypes":[FairysType.Wood, FairysType.Light, FairysType.Dark]}},
			"146":{"type":8, "ext":{"rate":0.25}},
			"147":{"type":16, "ext":{"orderTypes":[FairysType.Fire, FairysType.Water, FairysType.Wood, FairysType.Light, FairysType.Dark, 6]}},
			
			"148":{"type":11, "ext":{"friendBuffId":27}},
			"149":{"type":[13, 2], "ext":[{"enemyBuffId":22}, {"beforeType":FairysType.Light, "afterType":FairysType.Fire}]},
			"150":{"type":[2, 2], "ext":[{"beforeType":FairysType.Light, "afterType":FairysType.Water},{"beforeType":FairysType.Dark, "afterType":6}]},
			"151":{"type":[17, 2], "ext":[{"turnNum":2}, {"beforeType":7, "afterType":FairysType.Dark}]},
			
			"152":{"type":11, "ext":{"friendBuffId":28}},
			"153":{"type":8, "ext":{"rate":0.4}},
			"154":{"type":[9, 14], "ext":[{"type":FairysType.Light, "rate":50},{"type":FairysType.Light}]},
			"155":{"type":[9, 14], "ext":[{"type":FairysType.Dark, "rate":50},{"type":FairysType.Dark}]}
		};
		/**
		 * 注意：第一行数据不能删除
		 * "{0}":new FairyMainSkill({0}, "{1}", "{3}", handlers[{0}]),
		 */	
		public static const skills:Object = {
			"0":new FairyMainSkill(0, "", "无", handlers[0]),
			
			//----------------------------黄金分割线------------------------
			//exportData part begin

			"1":new FairyMainSkill(1, "火焰攻击", "对敌方全体造成自身攻击力5倍的火属性伤害", handlers[1]),
			"2":new FairyMainSkill(2, "烈焰攻击", "对敌方全体造成自身攻击力30倍的火属性伤害", handlers[2]),
			"3":new FairyMainSkill(3, "碧水攻击", "对敌方全体造成自身攻击力5倍的水属性伤害", handlers[3]),
			"4":new FairyMainSkill(4, "激流攻击", "对敌方全体造成自身攻击力30倍的水属性伤害", handlers[4]),
			"5":new FairyMainSkill(5, "烈风攻击", "对敌方全体造成自身攻击力5倍的木属性伤害", handlers[5]),
			"6":new FairyMainSkill(6, "盖亚攻击", "对敌方全体造成自身攻击力30倍的木属性伤害", handlers[6]),
			"7":new FairyMainSkill(7, "闪光攻击", "对敌方全体造成自身攻击力5倍的光属性伤害", handlers[7]),
			"8":new FairyMainSkill(8, "神圣攻击", "对敌方全体造成自身攻击力30倍的光属性伤害", handlers[8]),
			"9":new FairyMainSkill(9, "黑暗攻击", "对敌方全体造成自身攻击力5倍的暗属性伤害", handlers[9]),
			"10":new FairyMainSkill(10, "地狱攻击", "对敌方全体造成自身攻击力30倍的暗属性伤害", handlers[10]),
			"11":new FairyMainSkill(11, "攻击准备·火", "所有回复宝珠变化成火宝珠", handlers[11]),
			"12":new FairyMainSkill(12, "防御准备·水", "所有火宝珠变化成回复宝珠", handlers[12]),
			"13":new FairyMainSkill(13, "宝珠刷新", "所有宝珠随机变化", handlers[13]),
			"14":new FairyMainSkill(14, "防御准备·光", "所有暗宝珠变化成回复宝珠", handlers[14]),
			"15":new FairyMainSkill(15, "攻击准备·暗", "所有回复宝珠变化成暗宝珠", handlers[15]),
			"16":new FairyMainSkill(16, "回复之光", "HP回复300点", handlers[16]),
			"17":new FairyMainSkill(17, "防御姿态", "3回合内，受到伤害降低50%", handlers[17]),
			"18":new FairyMainSkill(18, "护甲破坏", "5回合内，所有敌人的防御力减少75%", handlers[18]),
			"19":new FairyMainSkill(19, "治愈之光", "HP回复500点", handlers[19]),
			"20":new FairyMainSkill(20, "火焰突击", "对敌方全体造成自身攻击力15倍的火属性伤害", handlers[20]),
			"21":new FairyMainSkill(21, "碧水突击", "对敌方全体造成自身攻击力15倍的水属性伤害", handlers[21]),
			"22":new FairyMainSkill(22, "烈风突击", "对敌方全体造成自身攻击力15倍的木属性伤害", handlers[22]),
			"23":new FairyMainSkill(23, "闪光突击", "对敌方全体造成自身攻击力15倍的光属性伤害", handlers[23]),
			"24":new FairyMainSkill(24, "黑暗突击", "对敌方全体造成自身攻击力15倍的暗属性伤害", handlers[24]),
			"25":new FairyMainSkill(25, "生命吸收", "对敌方一体造成伤害较大的伤害，并回复等值的生命值", handlers[25]),
			"26":new FairyMainSkill(26, "完全治愈", "将生命值回复到满值", handlers[26]),
			"27":new FairyMainSkill(27, "双重攻击准备", "所有回复宝珠和暗宝珠变成光宝珠", handlers[27]),
			"28":new FairyMainSkill(28, "暗黑之影", "扣除敌方全体当前生命值的30%", handlers[28]),
			"29":new FairyMainSkill(29, "爆炎怒涛", "对敌方单体造成自身攻击力50倍的火属性伤害", handlers[29]),
			"30":new FairyMainSkill(30, "至尊圣光", "对敌方全体造成自身攻击力40倍的光属性伤害", handlers[30]),
			"31":new FairyMainSkill(31, "神谕之光", "HP回复2000点", handlers[31]),
			"32":new FairyMainSkill(32, "妩媚", "令敌方全体的攻击回合数延后3回合", handlers[32]),
			"33":new FairyMainSkill(33, "防御准备·木", "所有水宝珠变化成回复宝珠", handlers[33]),
			"34":new FairyMainSkill(34, "治疗赞歌", "回复一定量的生命值", handlers[34]),
			"35":new FairyMainSkill(35, "治愈赞歌", "回复大量的生命值", handlers[35]),
			"36":new FairyMainSkill(36, "攻守逆转·暗", "所有光宝珠变化成回复宝珠，回复宝珠变成暗宝珠", handlers[36]),
			"37":new FairyMainSkill(37, "防御准备·水", "所有火宝珠变化成回复宝珠", handlers[37]),
			"38":new FairyMainSkill(38, "宝珠逆转·火", "所有水宝珠变化成火宝珠", handlers[38]),
			"39":new FairyMainSkill(39, "宝珠逆转·水", "所有木宝珠变化成水宝珠", handlers[39]),
			"40":new FairyMainSkill(40, "宝珠逆转·木", "所有火宝珠变化成木宝珠", handlers[40]),
			"41":new FairyMainSkill(41, "宝珠逆转·光", "所有暗宝珠变化成光宝珠", handlers[41]),
			"42":new FairyMainSkill(42, "宝珠逆转·暗", "所有光宝珠变化成暗宝珠", handlers[42]),
			"43":new FairyMainSkill(43, "火焰吐息", "对敌方全体造成自身攻击力10倍的火属性伤害", handlers[43]),
			"44":new FairyMainSkill(44, "冰泉吐息", "对敌方全体造成自身攻击力10倍的水属性伤害", handlers[44]),
			"45":new FairyMainSkill(45, "攻击准备·水", "所有回复宝珠变化成水宝珠", handlers[45]),
			"46":new FairyMainSkill(46, "攻击准备·木", "所有回复宝珠变化成木宝珠", handlers[46]),
			"47":new FairyMainSkill(47, "大地吐息", "对敌方全体造成自身攻击力10倍的木属性伤害", handlers[47]),
			"48":new FairyMainSkill(48, "攻击准备·火", "所有回复宝珠变化成火宝珠", handlers[48]),
			"49":new FairyMainSkill(49, "攻击准备·光", "所有回复宝珠变化成光宝珠", handlers[49]),
			"50":new FairyMainSkill(50, "攻击准备·暗", "所有回复宝珠变化成暗宝珠", handlers[50]),
			"51":new FairyMainSkill(51, "全军突击！", "对敌方全体造成5000点固定伤害攻击，无视防御", handlers[51]),
			"52":new FairyMainSkill(52, "萌杀拳", "对敌方全体造成505点木属性伤害", handlers[52]),
			"53":new FairyMainSkill(53, "海豚之舞", "对敌方一体造成伤害，并回复伤害值一半的生命值", handlers[53]),
			"54":new FairyMainSkill(54, "火之强化", "2回合内，火属性精灵的攻击力变为1.5倍", handlers[54]),
			"55":new FairyMainSkill(55, "水之强化", "2回合内，水属性精灵的攻击力变为1.5倍", handlers[55]),
			"56":new FairyMainSkill(56, "木之强化", "2回合内，木属性精灵的攻击力变为1.5倍", handlers[56]),
			"57":new FairyMainSkill(57, "光之强化", "2回合内，光属性精灵的攻击力变为1.5倍", handlers[57]),
			"58":new FairyMainSkill(58, "暗之强化", "2回合内，暗属性精灵的攻击力变为1.5倍", handlers[58]),
			"59":new FairyMainSkill(59, "圣光吐息", "对敌方全体造成自身攻击力10倍的光属性伤害", handlers[59]),
			"60":new FairyMainSkill(60, "高等防御", "3回合内，受到伤害降低75%", handlers[60]),
			"61":new FairyMainSkill(61, "火焰强化", "屏幕上所有火宝珠攻击力强化", handlers[61]),
			"62":new FairyMainSkill(62, "护甲损坏", "5回合内，所有敌人的防御力减少50%", handlers[62]),
			"63":new FairyMainSkill(63, "暗黑吐息", "对敌方全体造成自身攻击力10倍的暗属性伤害", handlers[63]),
			"64":new FairyMainSkill(64, "碧水强化", "屏幕上所有水宝珠攻击力强化", handlers[64]),
			"65":new FairyMainSkill(65, "玲珑幻化术", "3回合内，火属性伤害完全无效", handlers[65]),
			"66":new FairyMainSkill(66, "翠木强化", "屏幕上所有木宝珠攻击力强化", handlers[66]),
			"67":new FairyMainSkill(67, "暗夜毒袭", "使敌方全体中毒，直至死亡，伤害无视属性和防御", handlers[67]),
			"68":new FairyMainSkill(68, "暗夜剧毒", "使敌方全体中剧毒，直至死亡，伤害无视属性和防御", handlers[68]),
			"69":new FairyMainSkill(69, "神灭斩", "对敌方单体造成自身攻击力50倍的暗属性伤害", handlers[69]),
			"70":new FairyMainSkill(70, "圣光强化", "屏幕上所有光宝珠攻击力强化", handlers[70]),
			"71":new FairyMainSkill(71, "红莲破盾斩", "3回合内，所有敌人的防御力减少100%", handlers[71]),
			"72":new FairyMainSkill(72, "激流束缚", "令敌方全体的攻击回合数延后5回合", handlers[72]),
			"73":new FairyMainSkill(73, "幽冥强化", "屏幕上所有暗宝珠攻击力强化", handlers[73]),
			"74":new FairyMainSkill(74, "南瓜烟雾", "3回合内，木属性伤害完全无效", handlers[74]),
			"75":new FairyMainSkill(75, "防御准备·暗", "所有光宝珠变为回复宝珠", handlers[75]),
			"76":new FairyMainSkill(76, "彩虹糖变幻术", "所有回复宝珠变为暗宝珠，光宝珠变为回复宝珠", handlers[76]),
			"77":new FairyMainSkill(77, "姬神一击", "对敌方全体造成7777点固定伤害攻击，无视防御", handlers[77]),
			"78":new FairyMainSkill(78, "防御准备·火", "所有木宝珠变为回复宝珠", handlers[78]),
			"79":new FairyMainSkill(79, "双重水果变幻", "所有光宝珠和水宝珠变为暗宝珠", handlers[79]),
			"80":new FairyMainSkill(80, "慈爱之舞", "所有宝珠变为光宝珠", handlers[80]),
			"81":new FairyMainSkill(81, "火焰强袭", "所有水宝珠和回复宝珠变为火宝珠", handlers[81]),
			"82":new FairyMainSkill(82, "冰霜强袭", "所有木宝珠和回复宝珠变为水宝珠", handlers[82]),
			"83":new FairyMainSkill(83, "巨木强袭", "所有火宝珠和回复宝珠变为木宝珠", handlers[83]),
			"84":new FairyMainSkill(84, "雷电强袭", "所有暗宝珠和回复宝珠变为光宝珠", handlers[84]),
			"85":new FairyMainSkill(85, "暗黑强袭", "所有光宝珠和回复宝珠变为暗宝珠", handlers[85]),
			"86":new FairyMainSkill(86, "绝对神威", "扣除敌方全体当前生命值的35%", handlers[86]),
			"87":new FairyMainSkill(87, "火之逆转", "所有木宝珠变为火宝珠，所有回复宝珠变为木宝珠", handlers[87]),
			"88":new FairyMainSkill(88, "水之逆转", "所有火宝珠变为水宝珠，所有回复宝珠变为火宝珠", handlers[88]),
			"89":new FairyMainSkill(89, "木之逆转", "所有水宝珠变为木宝珠，所有回复宝珠变为水宝珠", handlers[89]),
			"90":new FairyMainSkill(90, "光之逆转", "所有暗宝珠变为光宝珠，所有回复宝珠变为暗宝珠", handlers[90]),
			"91":new FairyMainSkill(91, "暗之逆转", "所有光宝珠变为暗宝珠，所有回复宝珠变为光宝珠", handlers[91]),
			"92":new FairyMainSkill(92, "晓光之火", "所有光宝珠变为火宝珠", handlers[92]),
			"93":new FairyMainSkill(93, "暗夜之水", "所有暗宝珠变为水宝珠", handlers[93]),
			"94":new FairyMainSkill(94, "拂水之木", "所有水宝珠变为木宝珠", handlers[94]),
			"95":new FairyMainSkill(95, "栖木之光", "所有木宝珠变为光宝珠", handlers[95]),
			"96":new FairyMainSkill(96, "业火之暗", "所有火宝珠变为暗宝珠", handlers[96]),
			"97":new FairyMainSkill(97, "战女神的意志", "4回合内，队伍的回复力变为1.5倍", handlers[97]),
			"98":new FairyMainSkill(98, "仙女座之逆", "所有火宝珠变为水宝珠，所有回复宝珠变为木宝珠", handlers[98]),
			"99":new FairyMainSkill(99, "大地神护", "1回合内，受到的所有伤害减少75%", handlers[99]),
			"100":new FairyMainSkill(100, "十字焰阳", "对敌方单体造成攻击力20倍的光属性伤害，光属性宝珠攻击力强化", handlers[100]),
			"101":new FairyMainSkill(101, "紫月神箭", "对敌方单体造成攻击力20倍的暗属性伤害，暗属性宝珠攻击力强化", handlers[101]),
			"102":new FairyMainSkill(102, "双重宝珠变化・火木", "所有木宝珠变为火宝珠，所有回复宝珠变为木宝珠", handlers[102]),
			"103":new FairyMainSkill(103, "双重宝珠变化・水火", "所有火宝珠变为水宝珠，所有回复宝珠变为火宝珠", handlers[103]),
			"104":new FairyMainSkill(104, "双重宝珠变化・木水", "所有水宝珠变为木宝珠，所有回复宝珠变为水宝珠", handlers[104]),
			"105":new FairyMainSkill(105, "双重宝珠变化・光暗", "所有暗宝珠变为光宝珠，所有回复宝珠变为暗宝珠", handlers[105]),
			"106":new FairyMainSkill(106, "双重宝珠变化・暗光", "所有光宝珠变为暗宝珠，所有回复宝珠变为光宝珠", handlers[106]),
			"107":new FairyMainSkill(107, "冰淇淋群攻", "3回合内，所有攻击转化为全体攻击", handlers[107]),
			"108":new FairyMainSkill(108, "灵猫治愈", "回复相当于自身回复力6倍的生命值", handlers[108]),
			"109":new FairyMainSkill(109, "黯语冥猫术", "对敌方全体造成10倍攻击力的暗属性伤害，敌方攻击回合数延后1回合", handlers[109]),
			"110":new FairyMainSkill(110, "魅舞", "所有木宝珠和光宝珠变为回复宝珠", handlers[110]),
			"111":new FairyMainSkill(111, "灵梦", "所有火宝珠和暗宝珠变为回复宝珠", handlers[111]),
			"112":new FairyMainSkill(112, "鹿灵之舞", "所有水宝珠和光宝珠变为回复宝珠", handlers[112]),
			"113":new FairyMainSkill(113, "炽焰圣光", "水宝珠变为火宝珠，敌方攻击回合数延后1回合", handlers[113]),
			"114":new FairyMainSkill(114, "碧水圣光", "1回合内，水属性精灵的攻击力变为2.5倍", handlers[114]),
			"115":new FairyMainSkill(115, "岚风圣光", "暗宝珠变为木宝珠，敌方攻击回合数延后1回合", handlers[115]),
			"116":new FairyMainSkill(116, "烈阳圣光", "1回合内，光属性精灵的攻击力变为2.5倍", handlers[116]),
			"117":new FairyMainSkill(117, "混沌圣光", "1回合内，暗属性精灵的攻击力变为2.5倍", handlers[117]),
			"118":new FairyMainSkill(118, "四神之力", "扣除敌方全体当前生命值的20%", handlers[118]),
			"119":new FairyMainSkill(119, "烈焰之刃", "回复3000生命值，所有回复宝珠变为火宝珠", handlers[119]),
			"120":new FairyMainSkill(120, "圣枪决断", "光、木属性宝珠攻击力强化", handlers[120]),
			"121":new FairyMainSkill(121, "女王的嘲讽", "敌方全体的攻击回合数延后1回合，火属性宝珠攻击力强化", handlers[121]),
			"122":new FairyMainSkill(122, "灵之斩", "对敌方一体造成高伤害，并回复伤害值一半的生命值", handlers[122]),
			"123":new FairyMainSkill(123, "龙之斩", "对敌方一体造成高伤害，并回复伤害值一半的生命值", handlers[123]),
			"124":new FairyMainSkill(124, "7式圣光", "对敌方单体造成攻击力80倍的光属性伤害，木宝珠变为光宝珠", handlers[124]),
			"125":new FairyMainSkill(125, "0式封杀", "所有水宝珠变为暗宝珠，并令敌方全体的攻击回合数延后1回合", handlers[125]),
			"126":new FairyMainSkill(126, "白羊之印", "1回合内，回复类型精灵攻击力变为1.5倍，敌方攻击延后一回合", handlers[126]),
			"127":new FairyMainSkill(127, "金牛之印", "1回合内，体力类型精灵攻击力变为1.5倍，敌方攻击延后一回合", handlers[127]),
			"128":new FairyMainSkill(128, "摩羯之印", "1回合内，攻击类型精灵攻击力变为1.5倍，所有回复宝珠变为光宝珠", handlers[128]),
			"129":new FairyMainSkill(129, "酷蛋之盾", "5回合内，受到所有伤害降低50%", handlers[129]),
			"130":new FairyMainSkill(130, "圣·白羊之印", "1回合内，回复类型精灵攻击力变为2倍，敌方攻击延后一回合", handlers[130]),
			"131":new FairyMainSkill(131, "圣·金牛之印", "1回合内，体力类型精灵攻击力变为2倍，敌方攻击延后一回合", handlers[131]),
			"132":new FairyMainSkill(132, "圣·摩羯之印", "1回合内，攻击类型精灵攻击力变为2倍，所有回复宝珠变为光宝珠", handlers[132]),
			"133":new FairyMainSkill(133, "双子之印", "所有暗宝珠变为光宝珠，所有回复宝珠变为暗宝珠", handlers[133]),
			"134":new FairyMainSkill(134, "风火结界", "屏幕上所有宝珠变为火宝珠和暗宝珠", handlers[134]),
			"135":new FairyMainSkill(135, "巨蟹之印", "1回合内，平衡类型精灵攻击力变为1.5倍，敌方攻击延后一回合", handlers[135]),
			"136":new FairyMainSkill(136, "天蝎之印", "1回合内，精英类型精灵攻击力变为1.5倍，回复宝珠变为暗宝珠", handlers[136]),
			"137":new FairyMainSkill(137, "处女之印", "一回合内，受到的所有伤害变为0", handlers[137]),
			"138":new FairyMainSkill(138, "水瓶之印", "回复20%最大生命值，水属性宝珠攻击力强化", handlers[138]),
			"139":new FairyMainSkill(139, "狮子之印", "屏幕上所有水宝珠变为火宝珠，回复宝珠变为水宝珠", handlers[139]),
			"140":new FairyMainSkill(140, "双鱼之印", "屏幕上所有光宝珠变为暗宝珠，回复宝珠变为光宝珠", handlers[140]),
			"141":new FairyMainSkill(141, "天秤之印", "屏幕上所有暗宝珠变为光宝珠，回复宝珠变为暗宝珠", handlers[141]),
			"142":new FairyMainSkill(142, "射手之印", "一回合内，受到的所有伤害变为0", handlers[142]),
			"143":new FairyMainSkill(143, "无双龙阵", "屏幕上所有宝珠变为火宝珠、木宝珠和暗宝珠", handlers[143]),
			"144":new FairyMainSkill(144, "水雷龙阵", "屏幕上所有宝珠变为水宝珠、火宝珠和光宝珠", handlers[144]),
			"145":new FairyMainSkill(145, "武圣龙阵", "屏幕上所有宝珠变为木宝珠、光宝珠和暗宝珠", handlers[145]),
			"146":new FairyMainSkill(146, "铃动魔音", "扣除敌方全体当前生命值的25%", handlers[146]),
			"147":new FairyMainSkill(147, "赤壁之战", "屏幕上所有宝珠变为火、水、木、光、暗和回复六种宝珠", handlers[147]),
			"148":new FairyMainSkill(148, "箭风诛杀", "一回合内，木属性和光属性精灵攻击力变为2倍", handlers[148]),
			"149":new FairyMainSkill(149, "霸", "屏幕上光宝珠变为火宝珠，且一回合内所有敌人的防御力减少50%", handlers[149]),
			"150":new FairyMainSkill(150, "伊人之怜", "屏幕上所有光宝珠变为水宝珠，所有暗宝珠变为回复宝珠", handlers[150]),
			"151":new FairyMainSkill(151, "枭雄破空", "解除所有精灵封锁状态2回合，且屏幕上所有废珠变为暗宝珠", handlers[151]),
			"152":new FairyMainSkill(152, "天付良缘", "2回合内受到的伤害降低60%", handlers[152]),
			"153":new FairyMainSkill(153, "缘薄分浅", "扣除敌方全体当前生命的40%", handlers[153]),
			"154":new FairyMainSkill(154, "神光降临", "对敌方单体造成攻击力50倍的光属性伤害，光属性宝珠攻击力超强化", handlers[154]),
			"155":new FairyMainSkill(155, "暗夜降临", "对敌方单体造成攻击力50倍的暗属性伤害，暗属性宝珠攻击力超强化", handlers[155])

			//exportData part end
		};
		
		public static const handlerTypes:Object = {
			"0":"",
			//造成精灵攻击力多少倍的某属性全体伤害，参数 rate攻击力倍数，type属性类型
			"1":"mmo.fairybattle.skill.mainskillHandler.MainSkillAllRateAtkHandler",
			//所有A属性的宝珠转变为B属性的宝珠，参数 beforeType需要被转化的属性, afterType转化之后的属性
			"2":"mmo.fairybattle.skill.mainskillHandler.MainSkillChangeCubeHandler",
			//刷新所有宝珠
			"3":"mmo.fairybattle.skill.mainskillHandler.MainSkillRefreshCubeHandler",
			//回复固定数值的血，参数 value回复的血量
			"4":"mmo.fairybattle.skill.mainskillHandler.MainSkillStaticRecoverHandler",
			//延长对方CD ，参数 addTurn 延长的回合数
			"5":"mmo.fairybattle.skill.mainskillHandler.MainSkillAddEnemyCdHandler",
			//按全体血量的比例回血，rate:比例
			"6":"mmo.fairybattle.skill.mainskillHandler.MainSkillFullRecoverHandler",
			//吸血攻击，造成精灵攻击力x倍的攻击，产生伤害某百分比的吸血效果，参数"rate":攻击力倍数, "recoverRate":伤害的百分比
			"7":"mmo.fairybattle.skill.mainskillHandler.MainSkillLifeStealHandler",
			//扣除所有敌人百分比的血量， 参数 rate:扣血百分比
			"8":"mmo.fairybattle.skill.mainskillHandler.MainSkillPercentDamageHandler",
			//造成精灵攻击力多少倍的某属性单体伤害，参数 rate攻击力倍数，type属性类型
			"9":"mmo.fairybattle.skill.mainskillHandler.MainSkillSingleRateAtkHandler",
			//回复全队总回复力x倍的生命值，参数 rate 倍率
			"10":"mmo.fairybattle.skill.mainskillHandler.MainSkillRateRecoverHandler",
			//套一个友方buff,参数friendBuffId 友方buffID
			"11":"mmo.fairybattle.skill.mainskillHandler.MainSkillFriendBuffHandler",
			//造成固定数值的全体伤害 "damage":伤害数值, "directDamage":是否无视防御, "type":攻击属性类型
			"12":"mmo.fairybattle.skill.mainskillHandler.MainSkillStaticAllAtkHandler",
			//套一个敌方buff,参数enemyBuffId 敌方buffID
			"13":"mmo.fairybattle.skill.mainskillHandler.MainSkillEnemyBuffHandler",
			//某属性的宝珠强化 type：强化宝珠的属性类型
			"14":"mmo.fairybattle.skill.mainskillHandler.MainSkillCubePowerUpHandler",
			//回复释放者回复力x倍的生命值，参数 rate 倍率
			"15":"mmo.fairybattle.skill.mainskillHandler.MainSkillCasterRateRecoverHandler",
			//全屏珠子转成指定类型珠子（默认最少3颗），参数 orderTypes 类型数组
			"16":"mmo.fairybattle.skill.mainskillHandler.MainSkillChangeCubeToOrderTypesHandler",
			//解封X个回合，参数 turnNum 解封回合数
			"17":"mmo.fairybattle.skill.mainskillHandler.MainSkillUnBanHandler"
			
		}
	}
}
